path_labels: "/Users/YaVolkonskiy/Documents/001_Projects/003_tomato/001_data/005_Разметка/001_Pool_detect_leaf_Сбер/001_Сбер_разметка_24_09_24/yolo_format_Сегментация кустов томатов_calibration"
path_images: "/Users/YaVolkonskiy/Documents/001_Projects/003_tomato/001_data/005_Разметка/001_Pool_detect_leaf_Сбер/001_Сбер_разметка_24_09_24/imgs"

labelst_part_path: "/data/local-files/?d=Users/YaVolkonskiy/Documents/001_Projects/003_tomato/001_data/005_%D0%A0%D0%B0%D0%B7%D0%BC%D0%B5%D1%82%D0%BA%D0%B0/001_Pool_detect_leaf_%D0%A1%D0%B1%D0%B5%D1%80/001_%D0%A1%D0%B1%D0%B5%D1%80_%D1%80%D0%B0%D0%B7%D0%BC%D0%B5%D1%82%D0%BA%D0%B0_24_09_24/imgs/"
file_label_studio: 'project_label_studio.json'

