selected_images: ["GX010034_14.jpg",
                 "GX010040_19.jpg",
                 "GX010034_10.jpg",
                 "GX010035_50.jpg",
                 "GX010044_4.jpg",
                 "GX010038_1.jpg",
                 "GX010045_15.jpg",
                 "GX010046_6.jpg",
                 "GX010045_17.jpg",
                 "GX010044_6.jpg",
                 "GX010045_17.jpg",
                 "GX010044_6.jpg",
                 "GX010040_31.jpg",
                 "GX010038_17.jpg",
                 "GX010045_29.jpg",
                 "GX010044_5.jpg",
                 "GX010040_3.jpg",
                 "GX010042_1.jpg",
                 "GX010032_8.jpg"]

# It is so important not forget point class background
classes : {"leaf":1,
            "stem":2,
            "tomato":3}

LS_json_path: /Users/YaVolkonskiy/Documents/001_Projects/003_tomato/001_data/001_raw_data/002_video_data_customer/002_labeled/labeled_Olga_Gelya_21_11_23/project-13-at-2023-11-21-11-39-a223ddf0.json
dst_anot: "/Users/YaVolkonskiy/Documents/006_git/label-studio/006_LS_ImageMaskLabel_paddle_seg/data/Annotations_gray/"
